### ISSUE TITLE
Color props not being used/implemented

### ISSUE THREAD

**Issue by joeyfigaro** [vdelacou/iblis-react-native-undraw#4]
Hey there—thanks for taking the time to put together this library! 💪 

It looks like `accentcolor`, `haircolor`, `skincolor`, etc. are not being used in at least the `SVGOrganizePhotos` component, making it impossible to change the colors used in the illustration.

Can take a crack at putting up a PR if you'd be interested.

**Comment by vdelacou** [comment]
Hello Joey,

Thank you for your message, yes I create a script to replace the `accentcolor`, `haircolor`, `skincolor` with the mainly used color in `undraw` but it's true for some SVG, these colors are not the mainly used, so the color props doesn't work as expected

If you do a pull request for the  SVG you use, it could be great! 

Thank you so much
