### ISSUE TITLE
unDraw License 

### ISSUE THREAD

**Issue by anges244** [vdelacou/iblis-react-native-undraw#8]
Hi @vdelacou, first of all I'm really happy you like unDraw! There is a problem however with this library as it is violation with our [license](https://undraw.co/license) at unDraw. 

There are many reasons that made us adopt that license, including the automated scraping of all the illustrations for each library which makes the CDN bills much higher. After all, it’s Katerina’s right to decide how to distribute her work and her illustrations are updated many times throughout their lifecycle so having packs distributed, kind of defeats the purpose.

So I would kindly ask that you remove the bulk of the illustrations from the src, the scraper completely and the "Have up-to-date illustrations" part of the description and instead instruct the library users on how to replace the sample illustrations with new ones.

**Comment by vdelacou** [comment]
Dear Aggelos.

I am so sorry, I didn't know. I was thinking I can use undraw as I want

I will delete it !

Thank you so much for your kind message


Vincent DELACOURT
-------------------------------------
Email : vincent.delacourt@gmail.com
Cell: (+86) 132 62 63 42 67
Skype : vdelacou
Wechat: vincent_delacourt

**Comment by vdelacou** [comment]
Dear Aggelos,

I just did it.

Let me know if there are any problems!

Thank you
Vincent DELACOURT
-------------------------------------
Email : vincent.delacourt@gmail.com
Cell: (+86) 132 62 63 42 67
Skype : vdelacou
Wechat: vincent_delacourt
